### ISSUE TITLE
error in visualstudio.com build 

### ISSUE THREAD

**Issue by wujun4code** [jakobehn/VSTSGitHubTasks#12]
```
2017-01-12T07:14:36.2082533Z ##[section]Starting: Publish GitHub Release v20170112.2
2017-01-12T07:14:36.2092531Z ==============================================================================
2017-01-12T07:14:36.2092531Z Task         : Publish GitHub Release
2017-01-12T07:14:36.2092531Z Description  : Publish GitHub Release including uploading assets
2017-01-12T07:14:36.2092531Z Version      : 0.10.1
2017-01-12T07:14:36.2092531Z Author       : Jakob Ehn
2017-01-12T07:14:36.2092531Z Help         : [More Information](https://github.com/jakobehn/VSTSGitHubTasks)
2017-01-12T07:14:36.2092531Z ==============================================================================
2017-01-12T07:14:36.2102529Z Preparing task execution handler.
2017-01-12T07:14:36.6752537Z Executing the powershell script: C:\a\_tasks\PublishGitHubRelease_52a55b38-da88-4272-9cb5-8627a5197311\0.10.1\PublishGitHubRelease.ps1
2017-01-12T07:14:37.2832536Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'GitSourceUrl' because it is an empty string.
2017-01-12T07:14:37.2832536Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
2017-01-12T07:14:37.2832536Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2017-01-12T07:14:37.2832536Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2017-01-12T07:14:37.2832536Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-01-12T07:14:37.2992527Z ##[error]PowerShell script completed with 1 errors.
2017-01-12T07:14:37.2992527Z ##[section]Finishing: Publish GitHub Release v20170112.2

```

**Comment by wujun4code** [comment]
![image](https://cloud.githubusercontent.com/assets/5119542/21880802/ce33089a-d8db-11e6-988c-cff425505fef.png)

missing the input parameters `GitSourceUrl`

**Comment by wujun4code** [comment]
![image](https://cloud.githubusercontent.com/assets/5119542/21880826/f2f28c78-d8db-11e6-8c29-d565a08822f7.png)

missing the input parameters `GitSourceUrl`

**Comment by jessehouwing** [comment]
Running into the same issues.

**Comment by jessehouwing** [comment]
Workaround:
* Set to "External" enter a value in "Git source Url", save the definition.
* Set back to github, save the definition.

Alternate workaround
* delete task from current pipeline and add again to have the default value (null) be populated.

Caused by:
* No default value provided for Git Source Url, causing funny behavior when task is updated.

**Comment by jakobehn** [comment]
Uploaded new version with correct PS code  (0.10.3)

**Comment by wujun4code** [comment]
I tried the latest version, there is no errors now.
Thanks @jakobehn .
