### ISSUE TITLE
Octokit.NotFoundException while trying to publish

### ISSUE THREAD

**Issue by AndrewMarkley** [jakobehn/VSTSGitHubTasks#18]
This extension keeps throwing ##[error]Octokit.NotFoundException: Not Found when trying to use it.

```
2017-05-07T04:23:36.9593485Z ##[section]Starting: Publish GitHub Release Web Release 20170507.1
2017-05-07T04:23:36.9703692Z ==============================================================================
2017-05-07T04:23:36.9703692Z Task         : Publish GitHub Release
2017-05-07T04:23:36.9703692Z Description  : Publish GitHub Release including uploading assets
2017-05-07T04:23:36.9703692Z Version      : 0.10.3
2017-05-07T04:23:36.9703692Z Author       : Jakob Ehn
2017-05-07T04:23:36.9703692Z Help         : [More Information](https://github.com/jakobehn/VSTSGitHubTasks)
2017-05-07T04:23:36.9703692Z ==============================================================================
2017-05-07T04:23:36.9933428Z Preparing task execution handler.
2017-05-07T04:23:39.6231312Z Executing the powershell script: d:\a\_tasks\PublishGitHubRelease_52a55b38-da88-4272-9cb5-8627a5197311\0.10.3\PublishGitHubRelease.ps1
2017-05-07T04:23:40.6586177Z ##[error]Octokit.NotFoundException: Not Found
2017-05-07T04:23:40.6586177Z    at Octokit.Connection.HandleErrors(IResponse response)
2017-05-07T04:23:40.6586177Z    at Octokit.Connection.<RunRequest>d__51.MoveNext()
2017-05-07T04:23:40.6586177Z --- End of stack trace from previous location where exception was thrown ---
2017-05-07T04:23:40.6586177Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-05-07T04:23:40.6586177Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-07T04:23:40.6586177Z    at Octokit.Connection.<Run>d__50`1.MoveNext()
2017-05-07T04:23:40.6586177Z --- End of stack trace from previous location where exception was thrown ---
2017-05-07T04:23:40.6586177Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-05-07T04:23:40.6586177Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-05-07T04:23:40.6586177Z    at Octokit.ApiConnection.<Post>d__17`1.MoveNext()
2017-05-07T04:23:40.6586177Z {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
2017-05-07T04:23:40.6776377Z ##[error]PowerShell script completed with 1 errors.
2017-05-07T04:23:40.6786234Z ##[section]Finishing: Publish GitHub Release Web Release 20170507.1
```

**Comment by tishion** [comment]
@jakobehn   I think the octokit needs to be updated.

**Comment by mvmcjr** [comment]
+1

**Comment by jakobehn** [comment]
PR Accepted and integrated in 0.11.0. Thanks!

**Comment by DimitarCC** [comment]
I am still getting the same error even with lates 0.11.1 version.
Any clue what is wrong?

**Comment by jakobehn** [comment]
No, haven't been able to reproduce it. Are you sure that you have the correct repo URL and the corresponding access token?

**Comment by DimitarCC** [comment]
Yes you were right! There was wrong repository name. It works just fine. Sorry for inconvenience!
