### ISSUE TITLE
Octokit.ApiValidationException: Validation Failed

### ISSUE THREAD

**Issue by cilerler** [jakobehn/VSTSGitHubTasks#20]
Any idea what it might be?

```
2017-11-10T14:04:57.3903648Z ==============================================================================
2017-11-10T14:04:57.3903648Z Task         : Publish GitHub Release
2017-11-10T14:04:57.3903648Z Description  : Publish GitHub Release including uploading assets
2017-11-10T14:04:57.3903648Z Version      : 0.11.1
2017-11-10T14:04:57.3903648Z Author       : Jakob Ehn
2017-11-10T14:04:57.3903648Z Help         : [More Information](https://github.com/jakobehn/VSTSGitHubTasks)
2017-11-10T14:04:57.3903648Z ==============================================================================
2017-11-10T14:04:57.4303690Z Preparing task execution handler.
2017-11-10T14:05:02.1278279Z Executing the powershell script: d:\a\_tasks\PublishGitHubRelease_52a55b38-da88-4272-9cb5-8627a5197311\0.11.1\PublishGitHubRelease.ps1
2017-11-10T14:05:03.3924093Z ##[error]Octokit.ApiValidationException: Validation Failed
2017-11-10T14:05:03.3924093Z    at Octokit.Connection.HandleErrors(IResponse response)
2017-11-10T14:05:03.3924093Z    at Octokit.Connection.<RunRequest>d__55.MoveNext()
2017-11-10T14:05:03.3924093Z --- End of stack trace from previous location where exception was thrown ---
2017-11-10T14:05:03.3924093Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-11-10T14:05:03.3924093Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-11-10T14:05:03.3924093Z    at Octokit.Connection.<Run>d__54`1.MoveNext()
2017-11-10T14:05:03.3924093Z --- End of stack trace from previous location where exception was thrown ---
2017-11-10T14:05:03.3924093Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-11-10T14:05:03.3924093Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-11-10T14:05:03.3924093Z    at Octokit.ApiConnection.<Post>d__22`1.MoveNext()
2017-11-10T14:05:03.3924093Z {"message":"Validation Failed","errors":[{"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not a valid tag"},{"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not well-formed"},{"resource":"Release","code":"custom","message":"Published releases must have a valid tag"}],"documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}
2017-11-10T14:05:03.4214094Z ##[error]PowerShell script completed with 1 errors.
```

**Comment by marceloavf** [comment]
I'm with the same problem
Have you done something to fix it @cilerler ?

**Comment by thomasgalliker** [comment]
Could it be that you tried to upload a release with a tag that already exists? Or the tag contains invalid characters? Follow the naming rules for git tags.
