### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by dangershony** [jakobehn/VSTSGitHubTasks#3]
I get this error in the vso logs

2016-06-30T15:22:04.0832101Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Assets' because it is null.
2016-06-30T15:22:04.0842074Z ##[error]   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
2016-06-30T15:22:04.0842074Z ##[error]   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2016-06-30T15:22:04.0852083Z ##[error]   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2016-06-30T15:22:04.0862099Z ##[error]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by Sebosek** [comment]
Same here. Any progress or support?

**Comment by Eynorey** [comment]
getting the same error - did anyone fix it yet?

**Comment by giuliov** [comment]
I set the Release variable `system.debug` to `true`, and found that the error is located in 

```
[bool]$draftBool= Convert-String $draft Boolean
[bool]$prereleaseBool= Convert-String $prerelease Boolean
```

anyway, the task will move on and do its job.

One trick is mark the Task as _Continue on error_ so the Build / Release is not marked as _Failed_.

**Comment by yannduran** [comment]
Still having this problem in December 2016

**Comment by jakobehn** [comment]
Sorry guys for the slow response to this, I've finally gotten around to complete the PR for this issue.
I've uploaded a new version (0.9.9) of the build task to the gallery
